version: 1.0.{build}

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

clone_depth: 1

# scripts that are called at very beginning, before repo cloning
init:
  git config --global core.autocrlf input

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(nuget_version)
  package_version: $(nuget_version)

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

configuration:
- Release

platform: Any CPU

# scripts to run before build
before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "%APPVEYOR_BUILD_FOLDER%\NorthwindKataRepository\NorthwindKataRepository.csproj" -c %CONFIGURATION%

test_script:
- dotnet test "%APPVEYOR_BUILD_FOLDER%\NorthwindKataRepository.Tests\NorthwindKataRepository.Tests.csproj" -c %CONFIGURATION%

# artifacts:
#  - path: 'coverage.xml'

#after_test:
#- pip install codecov 
#- codecov -X gcov -f %APPVEYOR_BUILD_FOLDER%\coverage.xml

cache:
- packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified